# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install .NET 8.0.x SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Restore dependencies (install Nuget packages)
      run: dotnet restore
      
    - name: Build and publish
      run: |
        dotnet build --no-restore
        dotnet publish -c Release -o ./publish
      
    - name: Upload app artifacts to Github
      uses: actions/upload-artifact@v4
      with:
        name: app-artifacts
        path: ./publish

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Download the artifacts from Github (from the build job)
      uses: actions/download-artifact@v4
      with:
        name: app-artifacts

    - name: Stop the application service
      run: |
        sudo systemctl stop github-actions-test.service        

    - name: Deploy the the application
      run: |
        sudo rm -Rf /opt/github-actions-test || true
        sudo cp -r /home/azureuser/actions-runner/_work/github-actions-test/github-actions-test/ /opt/github-actions-test        

    - name: Start the application service
      run: |
        sudo systemctl start github-actions-test.service        
